# Generated by Django 4.2.13 on 2024-08-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
